{
 "title": "Beam",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Beam (SpillOn)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\ntimestamp as time,\n-- value[1] as \"FT\",\n-- value[2] as \"TM\",\n-- value[3] as \"SYIM\",\n-- value[4] as \"BHT\",\n-- value[5] as \"T0\",\n-- value[6] as \"AC\",\n-- value[7] as \"T1\",\n-- value[8] as \"DEF\",\n-- value[9] as \"Veto\",\n-- value[10] as \"Calori\",\n-- value[11] as \"BTC\",   \n-- value[12] as \"CDH1\",          \n-- value[13] as \"CDH2\",\n-- value[14] as \"CDH3\",\n-- value[15] as \"NC\",\n-- value[16] as \"CVC\",\nvalue[17] as \"BeamAsBHTxT0\",\nvalue[18] as \"BeamAsT0xT1\",\nvalue[19] as \"BeamAsT1xDEF\",\nvalue[20] as \"Kaon1\",\nvalue[21] as \"Kaon2\",\nvalue[22] as \"Kaon3\",\nvalue[23] as \"pion1\",\nvalue[24] as \"pion2\",\nvalue[25] as \"proton\",\nvalue[26] as \"electron\",\n--value[27] as \"KaonxCDH1\",\n--value[28] as \"KaonxCDH2\",\n--value[29] as \"KaonxCDH3\",\n-- value[30] as \"KaonxCDH1xg\",\n-- value[31] as \"PionxCDH1\",\n-- value[32] as \"Calori_cosmic\",\n-- value[33] as \"SpillStart\",\n-- value[34] as \"SpillEnd\",\n-- value[35] as BeamPrescaled,\n-- value[36] as \"PionPrescaled\",\n-- value[37] as \"Kaon2Prescaled\",\n-- value[38] as \"Kaon3Prescaled\",\nvalue[39] as \"KaonxCDH1_trig\",\nvalue[40] as \"KaonxCDH2_trig\",\nvalue[41] as \"KaonxCDH3_trig\",\nvalue[42] as \"KaonxCDH1xg_trig\",\nvalue[43] as \"Kaonxgamma_trig\",\nvalue[44] as \"PionxCDH_trig\",\n-- value[45] as \"PionxPbF2_trig\",\n-- value[46] as \"ElectronPrescaled\",\n-- value[47] as \"CDH_cosmic\",\n-- value[48] as \"ProtonPrescaled\",\nvalue[49] as \"Request\",\nvalue[50] as \"Accept\",\nvalue[51] as \"RealTime\",\nvalue[52] as \"DeadTime\"\n-- value[53] as \"Clock10kHz\",\n-- value[54] as \"tmp54\",\n-- value[55] as \"tmp55\",\n-- value[56] as \"tmp56\",\n-- value[57] as \"tmp57\",\n-- value[58] as \"tmp58\",\n-- value[59] as \"tmp59\",\n-- value[60] as \"tmp60\",\n-- value[61] as \"tmp61\",\n-- value[62] as \"tmp62\",\n-- value[63] as \"tmp63\",\n-- value[64] as \"ClockTrigger\"\nFROM\n(\nSELECT * FROM\n scaler\nWHERE trigger = 'SpillOn'\nORDER BY timestamp DESC\nLIMIT 400\n)\nAS A ORDER BY timestamp"
    }
   ]
  },
  {
   "title": "PPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" as time, pps_k18_cntr1_1s, pps_k18_cntr1_intg_hr, pps_k18br_cntr1_1s, pps_k18br_cntr1_intg_hr\n FROM beam\n"
    }
   ]
  },
  {
   "title": "Beam @T1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" as time, beam_t1_mean_x, beam_t1_mean_y, beam_t1_sigma_x, beam_t1_sigma_y\n FROM beam"
    }
   ]
  },
  {
   "title": "Radiation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "radusvh" } },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" as time, rad_org0201g, rad_org0201n, rad_org0202g, rad_org0202n\n FROM beam\n"
    }
   ]
  }
 ]
}