{
 "title": "KIKUSUI",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT output as blc1_output\nFROM kikusui\nWHERE ip_address = '192.168.1.121'\nORDER BY timestamp DESC\nLIMIT 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT meas_volt as blc1_vmon\nFROM kikusui\nWHERE ip_address = '192.168.1.121'\nORDER BY timestamp DESC\nLIMIT 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT meas_curr as blc1_imon\nFROM kikusui\nWHERE ip_address = '192.168.1.121'\nORDER BY timestamp DESC\nLIMIT 1\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT output as blc2_output\nFROM kikusui WHERE ip_address = '192.168.1.122'\nORDER BY timestamp DESC\nLIMIT 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT meas_volt as blc2_vmon\nFROM kikusui WHERE ip_address = '192.168.1.122'\nORDER BY timestamp DESC\nLIMIT 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT meas_curr as blc2_imon\nFROM kikusui WHERE ip_address = '192.168.1.122'\nORDER BY timestamp DESC\nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "SDC",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT output as sdc_output\nFROM kikusui WHERE ip_address = '192.168.1.123'\nORDER BY timestamp DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "SDC",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT meas_volt FROM kikusui WHERE ip_address = '192.168.1.123'\nORDER BY timestamp DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "SDC",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT meas_curr FROM kikusui WHERE ip_address = '192.168.1.123'\nORDER BY timestamp DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "BPC",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT output FROM kikusui WHERE ip_address = '192.168.1.124'\nORDER BY timestamp DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "BPC",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT meas_volt FROM kikusui WHERE ip_address = '192.168.1.124'\nORDER BY timestamp DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "BPC",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT meas_curr FROM kikusui WHERE ip_address = '192.168.1.124'\nORDER BY timestamp DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "CDC-U",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT output FROM kikusui WHERE ip_address = '192.168.1.125'\nORDER BY timestamp DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "CDC-U",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT meas_volt FROM kikusui WHERE ip_address = '192.168.1.125'\nORDER BY timestamp DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "CDC-U",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT meas_curr FROM kikusui WHERE ip_address = '192.168.1.125'\nORDER BY timestamp DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "CDC-D",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT output FROM kikusui WHERE ip_address = '192.168.1.126'\nORDER BY timestamp DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "CDC-D",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT meas_volt FROM kikusui WHERE ip_address = '192.168.1.126'\nORDER BY timestamp DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "CDC-D",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT meas_curr FROM kikusui WHERE ip_address = '192.168.1.126'\nORDER BY timestamp DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "KIKUSUI",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": " " } },
   "targets": [
    {
     "rawSql": "select\n  ip_address, timestamp, output, meas_volt, meas_curr\nfrom\n  (\nselect\n  *,\n  row_number() over (\n    partition by\n      ip_address\n    order by\n      timestamp desc\n  ) rownum\nfrom\n  kikusui\n) with_rownum\nWHERE rownum = 1\n;\n"
    }
   ]
  },
  {
   "title": "VMon",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  ip_address AS metric,\n  meas_volt\nFROM kikusui\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "IMon",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  ip_address AS metric,\n  meas_curr\nFROM kikusui\nORDER BY timestamp"
    }
   ]
  }
 ]
}