{
 "title": "Summary",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Accelerator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  run_number\n  FROM accelerator\n  ORDER BY timestamp DESC\n  LIMIT 1\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  hd_mode\n  FROM accelerator\n  ORDER BY timestamp DESC\n  LIMIT 1\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT mr_cycle, sx_spill_length\n  FROM accelerator\n  ORDER BY timestamp DESC\n  LIMIT 1\n"
    }
   ]
  },
  {
   "title": "Last update",
   "type": "stat",
   "gridPos": { "h": 2, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT * FROM\n(\nSELECT timestamp\n  FROM accelerator\n  ORDER BY timestamp DESC\n  LIMIT 1\n  ) AS A ORDER BY timestamp ASC;\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT mr_power, hd_power_syim\n  FROM accelerator\n  ORDER BY timestamp DESC\n  LIMIT 1\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 10, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT mr_intensity, hd_intensity_syim, hd_intensity_rgicm\n  FROM accelerator\n  ORDER BY timestamp DESC\n  LIMIT 1\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sx_duty, sx_extraction_efficiency\n  FROM accelerator\n  ORDER BY timestamp DESC\n  LIMIT 1\n"
    }
   ]
  },
  { "title": "Magnet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "BSM1",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "A" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\ncset, cmon\n  from magnet \nWHERE name = 'BSM1'\n  order by timestamp desc\nlimit 1"
    }
   ]
  },
  {
   "title": "K1.8D1",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "A" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\ncset, cmon\n  from magnet \nWHERE name = 'AK18D1'\n  order by timestamp desc\nlimit 1"
    }
   ]
  },
  {
   "title": "K1.8BR D5",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "A" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\ncset, cmon\n  from magnet \nWHERE name = 'K18BRD5'\n  order by timestamp desc\nlimit 1"
    }
   ]
  },
  {
   "title": "DORA",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "A" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\ncset, cmon\n  from magnet \nWHERE name = 'DORA'\n  order by timestamp desc\nlimit 1"
    }
   ]
  },
  {
   "title": "ESS1 POS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\nvset, vmon\n  from ess\nWHERE name = 'ESS1' AND electrode = 'POS'\n  order by timestamp desc\nlimit 1"
    }
   ]
  },
  {
   "title": "ESS1 NEG",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\nvset, vmon\n  from ess\nWHERE name = 'ESS1' AND electrode = 'NEG'\n  order by timestamp desc\nlimit 1"
    }
   ]
  },
  {
   "title": "K1.8BR D5",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "T" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\nfield\n  from magnet \nWHERE name = 'K18BRD5'\n  order by timestamp desc\nlimit 1"
    }
   ]
  },
  {
   "title": "DORA",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "T" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\nfield\n  from magnet \nWHERE name = 'DORA'\n  order by timestamp desc\nlimit 1"
    }
   ]
  },
  {
   "title": "CM1",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\ncset, cmon\n  from magnet \nWHERE name = 'K18CM1'\n  order by timestamp desc\nlimit 1"
    }
   ]
  },
  {
   "title": "CM2",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\ncset, cmon\n  from magnet \nWHERE name = 'K18CM2'\n  order by timestamp desc\nlimit 1"
    }
   ]
  },
  { "title": "Slit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "mm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\nifh_minus_cor, ifh_plus_cor, ifv_minus_cor, ifv_plus_cor,\nmom_minus_cor, mom_plus_cor, mass1_minus_cor, mass1_plus_cor\n  from slit\norder by timestamp desc\nlimit 1"
    }
   ]
  },
  { "title": "Gas/Air", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Gas In",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "SCCM" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value as gas_in FROM\n(\nSELECT value, timestamp\n  FROM gl840 \n  WHERE ip_address = '192.168.1.113' AND channel = 2\n  ORDER BY timestamp DESC\n  LIMIT 1\n  ) AS A ORDER BY timestamp ASC;\n"
    }
   ]
  },
  {
   "title": "Gas Out",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "SCCM" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value FROM\n(\nSELECT value, timestamp\n  FROM gl840 \n  WHERE ip_address = '192.168.1.113' AND channel = 3\n  ORDER BY timestamp DESC\n  LIMIT 1\n  ) AS A ORDER BY timestamp ASC;\n"
    }
   ]
  },
  {
   "title": "Apiste",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT tmon FROM\n(\nSELECT tmon, timestamp\n  FROM apiste \n  WHERE ip_address = '192.168.1.20'\n  ORDER BY timestamp DESC\n  LIMIT 1\n  ) AS A ORDER BY timestamp ASC;\n"
    }
   ]
  },
  {
   "title": "Room temp.",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value FROM\n(\nSELECT value, timestamp\n  FROM gl840 \n  WHERE ip_address = '192.168.1.113' AND channel = 4\n  ORDER BY timestamp DESC\n  LIMIT 1\n  ) AS A ORDER BY timestamp ASC;\n"
    }
   ]
  },
  {
   "title": "Room humi.",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value as room_humi FROM\n(\nSELECT value, timestamp\n  FROM gl840 \n  WHERE ip_address = '192.168.1.113' AND channel = 1\n  ORDER BY timestamp DESC\n  LIMIT 1\n  ) AS A ORDER BY timestamp ASC;\n"
    }
   ]
  },
  { "title": "HDDAQ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT run_number\n  FROM hddaq\n  ORDER BY timestamp DESC\n  LIMIT 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 3, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT start_time\n  FROM hddaq\n  ORDER BY timestamp DESC\n  LIMIT 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 15, "x": 9, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT comment\n  FROM hddaq\n  ORDER BY timestamp DESC\n  LIMIT 1"
    }
   ]
  }
 ]
}