{
 "title": "ESS",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "ESS1 POS VMON",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT vmon*1000 FROM\n(\nSELECT vmon, timestamp\n  FROM ess \n  WHERE name='ESS1' AND electrode='POS'\n  ORDER BY timestamp DESC\n  LIMIT 50 \n  ) AS A ORDER BY timestamp ASC;\n"
    }
   ]
  },
  {
   "title": "ESS1 NEG VMON",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT vmon*1000 FROM\n(\nSELECT vmon, timestamp\n  FROM ess \n  WHERE name='ESS1' AND electrode='NEG'\n  ORDER BY timestamp DESC\n  LIMIT 50 \n  ) AS A ORDER BY timestamp ASC;\n"
    }
   ]
  },
  {
   "title": "ESS2 POS VMON",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT vmon*1000 FROM\n(\nSELECT vmon, timestamp\n  FROM ess \n  WHERE name='ESS2' AND electrode='POS'\n  ORDER BY timestamp DESC\n  LIMIT 50 \n  ) AS A ORDER BY timestamp ASC;\n"
    }
   ]
  },
  {
   "title": "ESS2 NEG VMON",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT vmon*1000 FROM\n(\nSELECT vmon, timestamp\n  FROM ess \n  WHERE name='ESS2' AND electrode='NEG'\n  ORDER BY timestamp DESC\n  LIMIT 50 \n  ) AS A ORDER BY timestamp ASC;\n"
    }
   ]
  },
  {
   "title": "ESS1 POS IMON",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT imon*1e-6 FROM\n(\nSELECT imon, timestamp\n  FROM ess \n  WHERE name='ESS1' AND electrode='POS'\n  ORDER BY timestamp DESC\n  LIMIT 50 \n  ) AS A ORDER BY timestamp ASC;\n"
    }
   ]
  },
  {
   "title": "ESS1 NEG IMON",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT imon*1e-6 FROM\n(\nSELECT imon, timestamp\n  FROM ess \n  WHERE name='ESS1' AND electrode='NEG'\n  ORDER BY timestamp DESC\n  LIMIT 50 \n  ) AS A ORDER BY timestamp ASC;\n"
    }
   ]
  },
  {
   "title": "ESS2 POS IMON",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT imon*1e-6 FROM\n(\nSELECT imon, timestamp\n  FROM ess \n  WHERE name='ESS2' AND electrode='POS'\n  ORDER BY timestamp DESC\n  LIMIT 50 \n  ) AS A ORDER BY timestamp ASC;\n"
    }
   ]
  },
  {
   "title": "ESS2 NEG IMON",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT imon*1e-6 FROM\n(\nSELECT imon, timestamp\n  FROM ess \n  WHERE name='ESS2' AND electrode='NEG'\n  ORDER BY timestamp DESC\n  LIMIT 50 \n  ) AS A ORDER BY timestamp ASC;\n"
    }
   ]
  },
  {
   "title": "ESS VMON",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kvolt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  concat(name, ' ', left(electrode, 3)) AS metric,\n  vmon\nFROM ess\nWHERE vacuum is NULL AND \"timestamp\" >= NOW() - INTERVAL '1 week'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "ESS IMON",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  concat(name, ' ', left(electrode, 3)) AS metric,\n  imon*0.000001\nFROM ess\nWHERE vacuum is NULL AND \"timestamp\" >= NOW() - INTERVAL '1 week'\nORDER BY 1,2\n"
    }
   ]
  },
  {
   "title": "ESS1 VACUUM",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT vacuum FROM\n(\nSELECT vacuum, timestamp\n  FROM ess \n  WHERE name='ESS1' AND vacuum is NOT NULL\n  ORDER BY timestamp DESC\n  LIMIT 50 \n  ) AS A ORDER BY timestamp ASC;"
    }
   ]
  },
  {
   "title": "ESS2 VACUUM",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT vacuum FROM\n(\nSELECT vacuum, timestamp\n  FROM ess \n  WHERE name='ESS2' AND vacuum is NOT NULL\n  ORDER BY timestamp DESC\n  LIMIT 50 \n  ) AS A ORDER BY timestamp ASC;"
    }
   ]
  },
  {
   "title": "ESS VACUUM",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  name AS metric,\n  vacuum\nFROM ess\nWHERE vacuum is NOT NULL AND \"timestamp\" >= NOW() - INTERVAL '1 week'\nORDER BY 1,2"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 18, "w": 18, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "\n(SELECT * FROM\n(\n  SELECT timestamp, name, electrode, vset, vmon, imon\n  FROM ess\n  WHERE electrode IS NOT NULL\n    AND TO_NUMBER(TO_CHAR(timestamp, 'MI'), '99') = 0\n    AND TO_NUMBER(TO_CHAR(timestamp, 'SS'), '99') <= 10\n  ORDER BY timestamp DESC\n  LIMIT 4*12\n  )\n)\nORDER BY 1,2,3 DESC"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 18, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "targets": [
    {
     "rawSql": "\n(SELECT * FROM\n(\n  SELECT timestamp, name, vacuum\n  FROM ess\n  WHERE vacuum IS NOT NULL\n    AND TO_NUMBER(TO_CHAR(timestamp, 'MI'), '99') = 0\n    AND TO_NUMBER(TO_CHAR(timestamp, 'SS'), '99') <= 10\n  ORDER BY timestamp DESC\n  LIMIT 4*12\n  )\n)\nORDER BY 1,2,3 DESC"
    }
   ]
  }
 ]
}