{
 "title": "Scaler",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Primary beam",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\ntimestamp as time,\n-- value[1] as \"FT\",\nvalue[2] as \"TM\",\nvalue[3] as \"SYIM\"\nFROM\n(\nSELECT * FROM\n scaler\nWHERE trigger = 'SpillOn'\nORDER BY timestamp DESC\nLIMIT 400\n)\nAS A ORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Detector",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\ntimestamp as time,\n--value[1] as \"FT\",\n--value[2] as \"TM\",\n--value[3] as \"SYIM\",\nvalue[4] as \"BHT\",\nvalue[5] as \"T0\",\nvalue[6] as \"AC\",\nvalue[7] as \"T1\",\nvalue[8] as \"DEF\",\nvalue[9] as \"Veto\",\nvalue[10] as \"Calori\",\nvalue[11] as \"BTC\",   \nvalue[12] as \"CDH1\",          \nvalue[13] as \"CDH2\",\nvalue[14] as \"CDH3\",\nvalue[15] as \"NC\",\nvalue[16] as \"CVC\"\n-- value[17] as \"BeamAsBHTxT0\",\n-- value[53] as \"Clock10kHz\",\n-- value[54] as \"tmp54\",\n-- value[55] as \"tmp55\",\n-- value[56] as \"tmp56\",\n-- value[57] as \"tmp57\",\n-- value[58] as \"tmp58\",\n-- value[59] as \"tmp59\",\n-- value[60] as \"tmp60\",\n-- value[61] as \"tmp61\",\n-- value[62] as \"tmp62\",\n-- value[63] as \"tmp63\",\n-- value[64] as \"ClockTrigger\"\nFROM\n(\nSELECT * FROM\n scaler\nWHERE trigger = 'SpillOn'\nORDER BY timestamp DESC\nLIMIT 400\n)\nAS A ORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Beam (SpillOn)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\ntimestamp as time,\n-- value[1] as \"FT\",\n-- value[2] as \"TM\",\n-- value[3] as \"SYIM\",\n-- value[4] as \"BHT\",\n-- value[5] as \"T0\",\n-- value[6] as \"AC\",\n-- value[7] as \"T1\",\n-- value[8] as \"DEF\",\n-- value[9] as \"Veto\",\n-- value[10] as \"Calori\",\n-- value[11] as \"BTC\",   \n-- value[12] as \"CDH1\",          \n-- value[13] as \"CDH2\",\n-- value[14] as \"CDH3\",\n-- value[15] as \"NC\",\n-- value[16] as \"CVC\",\nvalue[17] as \"BeamAsBHTxT0\",\nvalue[18] as \"BeamAsT0xT1\",\nvalue[19] as \"BeamAsT1xDEF\",\nvalue[20] as \"Kaon1\",\nvalue[21] as \"Kaon2\",\nvalue[22] as \"Kaon3\",\nvalue[23] as \"pion1\",\nvalue[24] as \"pion2\",\nvalue[25] as \"proton\",\nvalue[26] as \"electron\"\n--value[27] as \"KaonxCDH1\",\n--value[28] as \"KaonxCDH2\",\n--value[29] as \"KaonxCDH3\",\n-- value[30] as \"KaonxCDH1xg\",\n-- value[31] as \"PionxCDH1\",\n-- value[32] as \"Calori_cosmic\",\n-- value[33] as \"SpillStart\",\n-- value[34] as \"SpillEnd\",\n-- value[35] as BeamPrescaled,\n-- value[36] as \"PionPrescaled\",\n-- value[37] as \"Kaon2Prescaled\",\n-- value[38] as \"Kaon3Prescaled\",\n-- value[39] as \"KaonxCDH1_trig\",\n-- value[40] as \"KaonxCDH2_trig\",\n-- value[41] as \"KaonxCDH3_trig\",\n-- value[42] as \"KaonxCDH1xg_trig\",\n-- value[43] as \"Kaonxgamma_trig\",\n-- value[44] as \"PionxCDH_trig\"\n-- value[45] as \"PionxPbF2_trig\",\n-- value[46] as \"ElectronPrescaled\",\n-- value[47] as \"CDH_cosmic\",\n-- value[48] as \"ProtonPrescaled\",\n-- value[49] as \"Request\",\n-- value[50] as \"Accept\",\n-- value[51] as \"RealTime\",\n-- value[52] as \"DeadTime\"\n-- value[53] as \"Clock10kHz\",\n-- value[54] as \"tmp54\",\n-- value[55] as \"tmp55\",\n-- value[56] as \"tmp56\",\n-- value[57] as \"tmp57\",\n-- value[58] as \"tmp58\",\n-- value[59] as \"tmp59\",\n-- value[60] as \"tmp60\",\n-- value[61] as \"tmp61\",\n-- value[62] as \"tmp62\",\n-- value[63] as \"tmp63\",\n-- value[64] as \"ClockTrigger\"\nFROM\n(\nSELECT * FROM\n scaler\nWHERE trigger = 'SpillOn'\nORDER BY timestamp DESC\nLIMIT 400\n)\nAS A ORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Trigger (SpillOn)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\ntimestamp as time,\n-- value[1] as \"FT\",\n-- value[2] as \"TM\",\n-- value[3] as \"SYIM\",\n-- value[4] as \"BHT\",\n-- value[5] as \"T0\",\n-- value[6] as \"AC\",\n-- value[7] as \"T1\",\n-- value[8] as \"DEF\",\n-- value[9] as \"Veto\",\n-- value[10] as \"Calori\",\n-- value[11] as \"BTC\",   \n-- value[12] as \"CDH1\",          \n-- value[13] as \"CDH2\",\n-- value[14] as \"CDH3\",\n-- value[15] as \"NC\",\n-- value[16] as \"CVC\",\n-- value[17] as \"BeamAsBHTxT0\",\n-- value[18] as \"BeamAsT0xT1\",\n-- value[19] as \"BeamAsT1xDEF\",\n-- value[20] as \"Kaon1\",\n-- value[21] as \"Kaon2\",\n-- value[22] as \"Kaon3\",\n-- value[23] as \"pion1\",\n-- value[24] as \"pion2\",\n-- value[25] as \"proton\",\n-- value[26] as \"electron\",\n-- value[27] as \"KaonxCDH1\",\n-- value[28] as \"KaonxCDH2\",\n-- value[29] as \"KaonxCDH3\",\n-- value[30] as \"KaonxCDH1xg\",\n-- value[31] as \"PionxCDH1\",\n-- value[32] as \"Calori_cosmic\",\n-- value[33] as \"SpillStart\",\n-- value[34] as \"SpillEnd\",\n-- value[35] as BeamPrescaled,\n-- value[36] as \"PionPrescaled\",\n-- value[37] as \"Kaon2Prescaled\",\n-- value[38] as \"Kaon3Prescaled\",\nvalue[39] as \"KaonxCDH1_trig\",\nvalue[40] as \"KaonxCDH2_trig\",\nvalue[41] as \"KaonxCDH3_trig\",\nvalue[42] as \"KaonxCDH1xg_trig\",\nvalue[43] as \"Kaonxgamma_trig\",\nvalue[44] as \"PionxCDH_trig\",\n-- value[45] as \"PionxPbF2_trig\",\n-- value[46] as \"ElectronPrescaled\",\n-- value[47] as \"CDH_cosmic\",\n-- value[48] as \"ProtonPrescaled\",\nvalue[49] as \"Request\",\nvalue[50] as \"Accept\",\nvalue[51] as \"RealTime\",\nvalue[52] as \"DeadTime\",\n-- value[53] as \"Clock10kHz\",\n-- value[54] as \"tmp54\",\n-- value[55] as \"tmp55\",\n-- value[56] as \"tmp56\",\n-- value[57] as \"tmp57\",\n-- value[58] as \"tmp58\",\n-- value[59] as \"tmp59\",\n-- value[60] as \"tmp60\",\n-- value[61] as \"tmp61\",\n-- value[62] as \"tmp62\",\n-- value[63] as \"tmp63\",\n-- value[64] as \"ClockTrigger\"\n1e4 * value[50] / value[49] as \"DAQ-Eff(‱)\"\nFROM\n(\nSELECT * FROM\n scaler\nWHERE trigger = 'SpillOn'\nORDER BY timestamp DESC\nLIMIT 400\n)\nAS A ORDER BY timestamp"
    }
   ]
  },
  {
   "title": "SpillOn",
   "type": "stat",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nvalue[1] as \"FT\",\nvalue[2] as \"TM\",\nvalue[3] as \"SYIM\",\nvalue[4] as \"BHT\",\nvalue[5] as \"T0\",\nvalue[6] as \"AC\",\nvalue[7] as \"T1\",\nvalue[8] as \"DEF\",\nvalue[9] as \"Veto\",\nvalue[10] as \"Calori\",\nvalue[11] as \"BTC\",   \nvalue[12] as \"CDH1\",          \nvalue[13] as \"CDH2\",\nvalue[14] as \"CDH3\",\nvalue[15] as \"NC\",\nvalue[16] as \"CVC\",\nvalue[17] as \"BeamAsBHTxT0\",\nvalue[18] as \"BeamAsT0xT1\",\nvalue[19] as \"BeamAsT1xDEF\",\nvalue[20] as \"Kaon1\",\nvalue[21] as \"Kaon2\",\nvalue[22] as \"Kaon3\",\nvalue[23] as \"pion1\",\nvalue[24] as \"pion2\",\nvalue[25] as \"proton\",\nvalue[26] as \"electron\",\nvalue[27] as \"KaonxCDH1\",\nvalue[28] as \"KaonxCDH2\",\nvalue[29] as \"KaonxCDH3\",\nvalue[30] as \"KaonxCDH1xg\",\nvalue[31] as \"PionxCDH1\",\nvalue[32] as \"Calori_cosmic\",\nvalue[33] as \"SpillStart\",\nvalue[34] as \"SpillEnd\",\nvalue[35] as BeamPrescaled,\nvalue[36] as \"PionPrescaled\",\nvalue[37] as \"Kaon2Prescaled\",\nvalue[38] as \"Kaon3Prescaled\",\nvalue[39] as \"KaonxCDH1_trig\",\nvalue[40] as \"KaonxCDH2_trig\",\nvalue[41] as \"KaonxCDH3_trig\",\nvalue[42] as \"KaonxCDH1xg_trig\",\nvalue[43] as \"Kaonxgamma_trig\",\nvalue[44] as \"PionxCDH_trig\",\nvalue[45] as \"PionxPbF2_trig\",\nvalue[46] as \"ElectronPrescaled\",\nvalue[47] as \"CDH_cosmic\",\nvalue[48] as \"ProtonPrescaled\",\nvalue[49] as \"Request\",\nvalue[50] as \"Accept\",\nvalue[51] as \"RealTime\",\nvalue[52] as \"DeadTime\",\nvalue[53] as \"Clock10kHz\",\n-- value[54] as \"tmp54\",\n-- value[55] as \"tmp55\",\n-- value[56] as \"tmp56\",\n-- value[57] as \"tmp57\",\n-- value[58] as \"tmp58\",\n-- value[59] as \"tmp59\",\n-- value[60] as \"tmp60\",\n-- value[61] as \"tmp61\",\n-- value[62] as \"tmp62\",\n-- value[63] as \"tmp63\",\nvalue[64] as \"ClockTrigger\",\n10000 * value[50] / value[49] as \"DAQ-Eff.(‱)\"\nFROM\n(\nSELECT * FROM\n scaler\nWHERE trigger = 'SpillOn'\nORDER BY timestamp DESC\nLIMIT 1\n)\nAS A ORDER BY timestamp"
    }
   ]
  },
  {
   "title": "SpillOff",
   "type": "stat",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nvalue[1] as \"FT\",\nvalue[2] as \"TM\",\nvalue[3] as \"SYIM\",\nvalue[4] as \"BHT\",\nvalue[5] as \"T0\",\nvalue[6] as \"AC\",\nvalue[7] as \"T1\",\nvalue[8] as \"DEF\",\nvalue[9] as \"Veto\",\nvalue[10] as \"Calori\",\nvalue[11] as \"BTC\",   \nvalue[12] as \"CDH1\",          \nvalue[13] as \"CDH2\",\nvalue[14] as \"CDH3\",\nvalue[15] as \"NC\",\nvalue[16] as \"CVC\",\nvalue[17] as \"BeamAsBHTxT0\",\nvalue[18] as \"BeamAsT0xT1\",\nvalue[19] as \"BeamAsT1xDEF\",\nvalue[20] as \"Kaon1\",\nvalue[21] as \"Kaon2\",\nvalue[22] as \"Kaon3\",\nvalue[23] as \"pion1\",\nvalue[24] as \"pion2\",\nvalue[25] as \"proton\",\nvalue[26] as \"electron\",\nvalue[27] as \"KaonxCDH1\",\nvalue[28] as \"KaonxCDH2\",\nvalue[29] as \"KaonxCDH3\",\nvalue[30] as \"KaonxCDH1xg\",\nvalue[31] as \"PionxCDH1\",\nvalue[32] as \"Calori_cosmic\",\nvalue[33] as \"SpillStart\",\nvalue[34] as \"SpillEnd\",\nvalue[35] as BeamPrescaled,\nvalue[36] as \"PionPrescaled\",\nvalue[37] as \"Kaon2Prescaled\",\nvalue[38] as \"Kaon3Prescaled\",\nvalue[39] as \"KaonxCDH1_trig\",\nvalue[40] as \"KaonxCDH2_trig\",\nvalue[41] as \"KaonxCDH3_trig\",\nvalue[42] as \"KaonxCDH1xg_trig\",\nvalue[43] as \"Kaonxgamma_trig\",\nvalue[44] as \"PionxCDH_trig\",\nvalue[45] as \"PionxPbF2_trig\",\nvalue[46] as \"ElectronPrescaled\",\nvalue[47] as \"CDH_cosmic\",\nvalue[48] as \"ProtonPrescaled\",\nvalue[49] as \"Request\",\nvalue[50] as \"Accept\",\nvalue[51] as \"RealTime\",\nvalue[52] as \"DeadTime\",\nvalue[53] as \"Clock10kHz\",\n-- value[54] as \"tmp54\",\n-- value[55] as \"tmp55\",\n-- value[56] as \"tmp56\",\n-- value[57] as \"tmp57\",\n-- value[58] as \"tmp58\",\n-- value[59] as \"tmp59\",\n-- value[60] as \"tmp60\",\n-- value[61] as \"tmp61\",\n-- value[62] as \"tmp62\",\n-- value[63] as \"tmp63\",\nvalue[64] as \"ClockTrigger\",\n10000 * value[50] / value[49] as \"DAQ-Eff.(‱)\"\nFROM\n(\nSELECT * FROM\n scaler\nWHERE trigger = 'SpillOff'\nORDER BY timestamp DESC\nLIMIT 400\n)\nAS A ORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Clock",
   "type": "stat",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nvalue[1] as \"FT\",\nvalue[2] as \"TM\",\nvalue[3] as \"SYIM\",\nvalue[4] as \"BHT\",\nvalue[5] as \"T0\",\nvalue[6] as \"AC\",\nvalue[7] as \"T1\",\nvalue[8] as \"DEF\",\nvalue[9] as \"Veto\",\nvalue[10] as \"Calori\",\nvalue[11] as \"BTC\",   \nvalue[12] as \"CDH1\",          \nvalue[13] as \"CDH2\",\nvalue[14] as \"CDH3\",\nvalue[15] as \"NC\",\nvalue[16] as \"CVC\",\nvalue[17] as \"BeamAsBHTxT0\",\nvalue[18] as \"BeamAsT0xT1\",\nvalue[19] as \"BeamAsT1xDEF\",\nvalue[20] as \"Kaon1\",\nvalue[21] as \"Kaon2\",\nvalue[22] as \"Kaon3\",\nvalue[23] as \"pion1\",\nvalue[24] as \"pion2\",\nvalue[25] as \"proton\",\nvalue[26] as \"electron\",\nvalue[27] as \"KaonxCDH1\",\nvalue[28] as \"KaonxCDH2\",\nvalue[29] as \"KaonxCDH3\",\nvalue[30] as \"KaonxCDH1xg\",\nvalue[31] as \"PionxCDH1\",\nvalue[32] as \"Calori_cosmic\",\nvalue[33] as \"SpillStart\",\nvalue[34] as \"SpillEnd\",\nvalue[35] as BeamPrescaled,\nvalue[36] as \"PionPrescaled\",\nvalue[37] as \"Kaon2Prescaled\",\nvalue[38] as \"Kaon3Prescaled\",\nvalue[39] as \"KaonxCDH1_trig\",\nvalue[40] as \"KaonxCDH2_trig\",\nvalue[41] as \"KaonxCDH3_trig\",\nvalue[42] as \"KaonxCDH1xg_trig\",\nvalue[43] as \"Kaonxgamma_trig\",\nvalue[44] as \"PionxCDH_trig\",\nvalue[45] as \"PionxPbF2_trig\",\nvalue[46] as \"ElectronPrescaled\",\nvalue[47] as \"CDH_cosmic\",\nvalue[48] as \"ProtonPrescaled\",\nvalue[49] as \"Request\",\nvalue[50] as \"Accept\",\nvalue[51] as \"RealTime\",\nvalue[52] as \"DeadTime\",\nvalue[53] as \"Clock10kHz\",\n-- value[54] as \"tmp54\",\n-- value[55] as \"tmp55\",\n-- value[56] as \"tmp56\",\n-- value[57] as \"tmp57\",\n-- value[58] as \"tmp58\",\n-- value[59] as \"tmp59\",\n-- value[60] as \"tmp60\",\n-- value[61] as \"tmp61\",\n-- value[62] as \"tmp62\",\n-- value[63] as \"tmp63\",\nvalue[64] as \"ClockTrigger\",\n10000 * value[50] / value[49] as \"DAQ-Eff.(‱)\"\nFROM\n(\nSELECT * FROM\n scaler\nWHERE trigger = 'Clock'\nORDER BY timestamp DESC\nLIMIT 400\n)\nAS A ORDER BY timestamp"
    }
   ]
  }
 ]
}