{
 "title": "Accelerator",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Run number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT run_number FROM\n(\nSELECT run_number, timestamp\n  FROM accelerator\n  ORDER BY timestamp DESC\n  LIMIT 1\n  ) AS A ORDER BY timestamp ASC;\n"
    }
   ]
  },
  {
   "title": "Shot number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT shot_number FROM\n(\nSELECT shot_number, timestamp\n  FROM accelerator\n  ORDER BY timestamp DESC\n  LIMIT 1\n  ) AS A ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Last update",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT * FROM\n(\nSELECT timestamp\n  FROM accelerator\n  ORDER BY timestamp DESC\n  LIMIT 1\n  ) AS A ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "MR Intensity (P3)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT mr_intensity FROM\n(\nSELECT mr_intensity, timestamp\n  FROM accelerator\n  ORDER BY timestamp DESC\n  LIMIT 1\n  ) AS A ORDER BY timestamp ASC;\n"
    }
   ]
  },
  {
   "title": "MR Operation cycle",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT mr_cycle FROM\n(\nSELECT mr_cycle, timestamp\n  FROM accelerator\n  ORDER BY timestamp DESC\n  LIMIT 1\n  ) AS A ORDER BY timestamp ASC;\n"
    }
   ]
  },
  {
   "title": "SX Duty",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sx_duty FROM\n(\nSELECT sx_duty, timestamp\n  FROM accelerator\n  ORDER BY timestamp DESC\n  LIMIT 1\n  ) AS A ORDER BY timestamp ASC;\n"
    }
   ]
  },
  {
   "title": "SX Spill length",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sx_spill_length FROM\n(\nSELECT sx_spill_length, timestamp\n  FROM accelerator\n  ORDER BY timestamp DESC\n  LIMIT 1\n  ) AS A ORDER BY timestamp ASC;\n"
    }
   ]
  },
  {
   "title": "SX Extraction efficiency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sx_extraction_efficiency FROM\n(\nSELECT sx_extraction_efficiency, timestamp\n  FROM accelerator\n  ORDER BY timestamp DESC\n  LIMIT 1\n  ) AS A ORDER BY timestamp ASC;\n"
    }
   ]
  },
  {
   "title": "MR Power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT mr_power FROM\n(\nSELECT mr_power, timestamp\n  FROM accelerator\n  ORDER BY timestamp DESC\n  LIMIT 1\n  ) AS A ORDER BY timestamp ASC;\n"
    }
   ]
  },
  {
   "title": "HD Power (SYIM)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT hd_power_syim FROM\n(\nSELECT hd_power_syim, timestamp\n  FROM accelerator\n  ORDER BY timestamp DESC\n  LIMIT 1\n  ) AS A ORDER BY timestamp ASC;\n"
    }
   ]
  },
  {
   "title": "HD Mode",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT hd_mode FROM\n(\nSELECT hd_mode, timestamp\n  FROM accelerator\n  ORDER BY timestamp DESC\n  LIMIT 1\n  ) AS A ORDER BY timestamp ASC;\n"
    }
   ]
  },
  {
   "title": "HD Intensity (SYIM)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT hd_intensity_syim FROM\n(\nSELECT hd_intensity_syim, timestamp\n  FROM accelerator\n  ORDER BY timestamp DESC\n  LIMIT 1\n  ) AS A ORDER BY timestamp ASC;\n"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" as time, mr_intensity, hd_intensity_syim, hd_intensity_rgicm\nFROM accelerator\nORDER BY timestamp DESC\n"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" as time,\n  sx_duty, sx_extraction_efficiency\nFROM accelerator\nORDER BY timestamp DESC\n"
    }
   ]
  },
  {
   "title": "HD Intensity (RGICM)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT hd_intensity_rgicm FROM\n(\nSELECT hd_intensity_rgicm, timestamp\n  FROM accelerator\n  ORDER BY timestamp DESC\n  LIMIT 1\n  ) AS A ORDER BY timestamp ASC;\n"
    }
   ]
  }
 ]
}