{
 "title": "CAENHV 1-01 (CDH 13-24u)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CAEN 1-1  A1733  12 Ch Pos. 4KV 2mA    Ser. 197 Rel. 3.01",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select\n  timestamp, channel, channel_name as name, v0set, i0set, vmon, imon, rup, rdown, channel_status as status\nfrom\n  (\nselect\n  *,\n  row_number() over (\n    partition by\n      channel\n    order by\n      timestamp desc\n  ) rownum\nfrom\n  caenhv\nWHERE\n  ip_address = '192.168.1.171'\n  AND board_slot = 1\n  AND channel_name != '-'\n) with_rownum\nWHERE rownum = 1\n;\n"
    }
   ]
  },
  {
   "title": "VMon",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  channel_name AS metric,\n  vmon\nFROM caenhv\nWHERE\n  ip_address = '192.168.1.171'\n  AND board_slot = 1\n  AND channel_name != '-'\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "IMon",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  channel_name AS metric,\n  imon*0.000001\nFROM caenhv\nWHERE\n  ip_address = '192.168.1.171'\n  AND board_slot = 1\n  AND channel_name != '-'\nORDER BY timestamp"
    }
   ]
  }
 ]
}