{
 "title": "Gas",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"font-size: 30px;\">\n<center>    ${__to:date:YYYY-MM-DD HH:mm:ss}\n</div>\n"
   }
  },
  { "title": "logger2 (GL840)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Flow",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "flowmlpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ch10_value FROM gl840\nWHERE ip_address LIKE 'logger2.%'\nORDER BY timestamp DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Differential pressure",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ch02_value FROM gl840\nWHERE ip_address LIKE 'logger2.%'\nORDER BY timestamp DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Oxygen content",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ch03_value FROM gl840\nWHERE ip_address LIKE 'logger2.%'\nORDER BY timestamp DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Dew point",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "°CTd" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ch04_value FROM gl840\nWHERE ip_address LIKE 'logger2.%'\nORDER BY timestamp DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Moisture content",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT 3.425e13 * EXP(-6137 / (ch04_value + 273.15)) FROM gl840\nWHERE ip_address LIKE 'logger2.%'\nORDER BY timestamp DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Room temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ch09_value FROM gl840\nWHERE ip_address LIKE 'logger2.%'\nORDER BY timestamp DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Inpurity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, ch03_value as oxygen, 3.425e13 * EXP(-6137 / (ch04_value + 273.15)) as moisture FROM gl840\nWHERE ip_address LIKE 'logger2.%'"
    }
   ]
  },
  {
   "title": "Differential pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, ch02_value as diffpres FROM gl840\nWHERE ip_address LIKE 'logger2.%'"
    }
   ]
  },
  {
   "title": "Room temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, ch09_value as roomtemp FROM gl840\nWHERE ip_address LIKE 'logger2.%'"
    }
   ]
  },
  {
   "title": "Inpurity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, ch03_value as oxygen, 3.425e13 * EXP(-6137 / (ch04_value + 273.15)) as moisture FROM gl840\nWHERE ip_address LIKE 'logger2.%'"
    }
   ]
  },
  {
   "title": "Differential pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, ch02_value as diffpres FROM gl840\nWHERE ip_address LIKE 'logger2.%'"
    }
   ]
  },
  {
   "title": "Room temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, ch09_value as roomtemp FROM gl840\nWHERE ip_address LIKE 'logger2.%'"
    }
   ]
  }
 ]
}