{
 "title": "HypTPC",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "imin", "query": "auto, 0, 7, 35, 65, 93, 120" },
   { "name": "imax", "query": "auto, 0, 11, 40, 68, 96" }
  ]
 },
 "panels": [
  { "title": "Spark", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last spark",
   "type": "dalvany-image-panel",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  concat('http://urazato.intra.j-parc.jp/spark/',\n         substring(filepath from '[^/]+$'),\n         '?v=', extract(epoch from \"timestamp\")::bigint) AS image_url\nFROM spark\nORDER BY \"timestamp\" DESC\nLIMIT 1;\n"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT timestamp as \"last spark\"\nFROM spark\nORDER BY \"timestamp\" DESC\nLIMIT 10"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "V" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, vmon as \"vmon_cat\" FROM caenhv WHERE board_slot = 2 and channel_name = 'Cathode' ORDER BY timestamp DESC LIMIT 1"
    },
    {
     "rawSql": "SELECT timestamp, vmon as \"vmon_gem\" FROM caenhv WHERE board_slot = 0 and channel_name = 'GEM' ORDER BY timestamp DESC LIMIT 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "uA" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, imon as \"imon_cat\" FROM caenhv WHERE board_slot = 2 and channel_name = 'Cathode' ORDER BY timestamp DESC LIMIT 1"
    },
    {
     "rawSql": "SELECT timestamp, imon as \"imon_gem\" FROM caenhv WHERE board_slot = 0 and channel_name = 'GEM' ORDER BY timestamp DESC LIMIT 1"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  COALESCE(SUM(imon) FILTER (WHERE board_slot = 2 and channel_name = 'Cathode'), 0)\n+ COALESCE(SUM(imon) FILTER (WHERE board_slot = 0 and channel_name = 'GEM'), 0) AS imon_total\nFROM caenhv\nWHERE ip_address = 'caenhv3'\n  AND $__timeFilter(timestamp)        -- Grafana なら有効\n  AND channel_name IN ('Cathode','GEM')\nGROUP BY 1\nORDER BY timestamp DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Spark (every 10 min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT t AS \"time\", n AS \"count\", GREATEST(n - sqrt(n), 0.0) AS \"lower\", n + sqrt(n) AS \"upper\" \nFROM ( SELECT time_bucket('10 min', \"timestamp\") + interval '5min' AS t, COALESCE(count(*), 0)::double precision AS n FROM spark WHERE $__timeFilter(\"timestamp\") GROUP BY 1 ) s ORDER BY 1 DESC\nLIMIT 100000"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "V" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, vmon as \"vmon_cat\" FROM caenhv WHERE board_slot = 2 and channel_name = 'Cathode'\nORDER BY timestamp DESC\nLIMIT 100000"
    },
    {
     "rawSql": "SELECT timestamp, vmon as \"vmon_gem\" FROM caenhv WHERE board_slot = 0 and channel_name = 'GEM'\nORDER BY timestamp DESC\nLIMIT 100000"
    }
   ]
  },
  {
   "title": "Spark (every 1 hour)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  t AS \"time\",\n  n                           AS \"count\",\n  GREATEST(n - sqrt(n), 0.0)  AS \"lower\",\n  n + sqrt(n)                 AS \"upper\"\nFROM (\n  SELECT\n    time_bucket('60 min', \"timestamp\") + interval '30 min' AS t,\n    COALESCE(count(*), 0)::double precision     AS n\n  FROM spark\n  WHERE $__timeFilter(\"timestamp\")\n  GROUP BY 1\n) s\nORDER BY 1 DESC\nLIMIT 100000\n"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "uA" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, imon as \"imon_cat\" FROM caenhv WHERE board_slot = 2 and channel_name = 'Cathode'\nORDER BY timestamp DESC\nLIMIT 100000"
    },
    {
     "rawSql": "SELECT timestamp, imon as \"imon_gem\" FROM caenhv WHERE board_slot = 0 and channel_name = 'GEM'\nORDER BY timestamp DESC\nLIMIT 100000"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  COALESCE(SUM(imon) FILTER (WHERE board_slot = 2 and channel_name = 'Cathode'), 0)\n+ COALESCE(SUM(imon) FILTER (WHERE board_slot = 0 and channel_name = 'GEM'), 0) AS imon_total\nFROM caenhv\nWHERE ip_address = 'caenhv3'\n  AND $__timeFilter(timestamp)        -- Grafana なら有効\n  AND channel_name IN ('Cathode','GEM')\nGROUP BY 1\nORDER BY 1 DESC\nLIMIT 100000\n"
    }
   ]
  }
 ]
}