{
 "title": "Prometheus",
 "description": "Server metrics using Prometheus",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - sum by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m]))\n         / sum by (instance) (rate(node_cpu_seconds_total[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MEM usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (instance, device) (\n  rate(node_network_receive_bytes_total{device!~\"lo|docker.*|veth.*|br.*|virbr.*|tun.*\"}[5m])\n)",
     "legendFormat": "{{instance}}-{{device}}-RX"
    },
    {
     "expr": "- sum by (instance, device) (\n  rate(node_network_transmit_bytes_total{device!~\"lo|docker.*|veth.*|br.*|virbr.*|tun.*\"}[5m])\n)",
     "legendFormat": "{{instance}}-{{device}}-TX"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (instance) (\n  rate(node_disk_read_bytes_total{device!~\"loop.*|ram.*|fd.*|sr.*|dm-.*|md.*|rbd.*\"}[5m])\n)",
     "legendFormat": "{{instance}}-read"
    },
    {
     "expr": "- sum by (instance) (\n  rate(node_disk_written_bytes_total{device!~\"loop.*|ram.*|fd.*|sr.*|dm-.*|md.*|rbd.*\"}[5m])\n)",
     "legendFormat": "{{instance}}-write"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{}",
     "legendFormat": "{{instance}}-{{chip}}-{{sensor}}"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - node_filesystem_avail_bytes{instance=\"geteb1\", mountpoint=\"/mnt/raid\"}\n           / node_filesystem_size_bytes{instance=\"geteb1\", mountpoint=\"/mnt/raid\"})",
     "legendFormat": "{{instance}}:{{mountpoint}}"
    },
    {
     "expr": "100 * (1 - node_filesystem_avail_bytes{mountpoint=\"/\"}\n           / node_filesystem_size_bytes{mountpoint=\"/\"})",
     "legendFormat": "{{instance}}:{{mountpoint}}"
    },
    {
     "expr": "100 * (1 - node_filesystem_avail_bytes{mountpoint=\"/home\"}\n           / node_filesystem_size_bytes{mountpoint=\"/home\"})",
     "legendFormat": "{{instance}}:{{mountpoint}}"
    },
    {}
   ]
  }
 ]
}