{
 "title": "SHS magnet",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"font-size: 30px;\">\n<center>    ${__to:date:YYYY-MM-DD HH:mm:ss}\n</div>\n"
   }
  },
  { "title": "Power Supply : Cryo Mag 4G", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp, iout, imag\nFROM\n  cryomag\nORDER BY\ntimestamp\nDESC\nLIMIT 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp, vout, vmag\nFROM\n  cryomag\nORDER BY\ntimestamp\nDESC\nLIMIT 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sweep, mode, ps_heater\nFROM\n  cryomag\nORDER BY\ntimestamp\nDESC\nLIMIT 1"
    }
   ]
  },
  { "title": "Ez-temp", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nai_ci_ps as \"Power supply electric current\",\nia_v_hall as \"V-Hall\"\nFROM\n  shs\nORDER BY\ntimestamp\nDESC\nLIMIT 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "T" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, field as probe1 FROM field WHERE name = 'shs1' ORDER BY timestamp DESC LIMIT 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "T" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, field as probe2 FROM field WHERE name = 'shs2' ORDER BY timestamp DESC LIMIT 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "kelvin" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nia_tcx01 as \"TCX01 Upper Coil bobbin\",\nia_tcx02 as \"TCX02 Bottom Coil bobbin\",\nia_tcx03 as \"TCX03 HTS_2nd (+)_U cernox\",\nia_tcx04 as \"TCX04 HTS_2nd (-)_B cernox\",\nia_tcx05 as \"TCX05 Cold head #1 2nd stage\",\nia_tcx06 as \"TCX06 Cold head #2 2nd stage\",\nia_tcx07 as \"TCX07 Cold head #1 1st stage\",\nia_tcx08 as \"TCX08 Cold head #2 1st stage\"\nFROM\n  shs\nORDER BY\ntimestamp\nDESC\nLIMIT 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kelvin" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nia_tsd09 as \"TSD09 Thermal shield bottom plate\",\nia_tsd10 as \"TSD10 Thermal shield outside Silicon\",\nia_tsd11 as \"TSD11 HTS_1st(+)_U Silicon diodes\",\nia_tsd12 as \"TSD11 HTS_1st(-)_B Silicon diodes\",\nai_tcc13 as \"TCC13 Thermal shield top plate RH\",\nai_tcc14 as \"TCC14 Thermal shield inside RH\",\nai_tcc15 as \"TCC15 Thermal shield outside RH\",\nai_tcc16 as \"TCC16 Thermal shield bottom plate RH\",\nai_tcc17 as \"TCC17 Thermal shield top plate LH\",\nai_tcc18 as \"TCC18 Thermal shield inside LH\",\nai_tcc19 as \"TCC19 Thermal shield outside LH\",\nai_tcc20 as \"TCC20 Thermal shield bottom plate LH\"\nFROM\n  shs\nORDER BY\ntimestamp\nDESC\nLIMIT 1"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "kelvin" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('5 minutes', \"timestamp\") AS \"time\",\n  avg(ia_tcx01) AS ia_tcx01,\n  avg(ia_tcx02) AS ia_tcx02,\n  avg(ia_tcx03) AS ia_tcx03,\n  avg(ia_tcx04) AS ia_tcx04,\n  avg(ia_tcx05) AS ia_tcx05,\n  avg(ia_tcx06) AS ia_tcx06,\n  avg(ia_tcx07) AS ia_tcx07,\n  avg(ia_tcx08) AS ia_tcx08,\n  avg(ia_tsd09) AS ia_tsd09,\n  avg(ia_tsd10) AS ia_tsd10,\n  avg(ia_tsd11) AS ia_tsd11,\n  avg(ia_tsd12) AS ia_tsd12,\n  avg(ai_tcc13) AS ai_tcc13,\n  avg(ai_tcc14) AS ai_tcc14,\n  avg(ai_tcc15) AS ai_tcc15,\n  avg(ai_tcc16) AS ai_tcc16,\n  avg(ai_tcc17) AS ai_tcc17,\n  avg(ai_tcc18) AS ai_tcc18,\n  avg(ai_tcc19) AS ai_tcc19,\n  avg(ai_tcc20) AS ai_tcc20\nFROM shs\nWHERE $__timeFilter(\"timestamp\")\nGROUP BY 1\nORDER BY 1;\n"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "kelvin" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('5 minutes', \"timestamp\") AS \"time\",\n  avg(ia_tcx01) AS ia_tcx01,\n  avg(ia_tcx02) AS ia_tcx02,\n  avg(ia_tcx03) AS ia_tcx03,\n  avg(ia_tcx04) AS ia_tcx04,\n  avg(ia_tcx05) AS ia_tcx05,\n  avg(ia_tcx06) AS ia_tcx06,\n  avg(ia_tcx07) AS ia_tcx07,\n  avg(ia_tcx08) AS ia_tcx08,\n  avg(ia_tsd09) AS ia_tsd09,\n  avg(ia_tsd10) AS ia_tsd10,\n  avg(ia_tsd11) AS ia_tsd11,\n  avg(ia_tsd12) AS ia_tsd12,\n  avg(ai_tcc13) AS ai_tcc13,\n  avg(ai_tcc14) AS ai_tcc14,\n  avg(ai_tcc15) AS ai_tcc15,\n  avg(ai_tcc16) AS ai_tcc16,\n  avg(ai_tcc17) AS ai_tcc17,\n  avg(ai_tcc18) AS ai_tcc18,\n  avg(ai_tcc19) AS ai_tcc19,\n  avg(ai_tcc20) AS ai_tcc20\nFROM shs\nWHERE $__timeFilter(\"timestamp\")\nGROUP BY 1\nORDER BY 1;\n"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "kelvin" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('5 minutes', \"timestamp\") AS \"time\",\n  avg(ia_tcx01) AS ia_tcx01,\n  avg(ia_tcx02) AS ia_tcx02,\n  avg(ia_tcx03) AS ia_tcx03,\n  avg(ia_tcx04) AS ia_tcx04,\n  avg(ia_tcx05) AS ia_tcx05,\n  avg(ia_tcx06) AS ia_tcx06,\n  avg(ia_tcx07) AS ia_tcx07,\n  avg(ia_tcx08) AS ia_tcx08,\n  avg(ia_tsd09) AS ia_tsd09,\n  avg(ia_tsd10) AS ia_tsd10,\n  avg(ia_tsd11) AS ia_tsd11,\n  avg(ia_tsd12) AS ia_tsd12,\n  avg(ai_tcc13) AS ai_tcc13,\n  avg(ai_tcc14) AS ai_tcc14,\n  avg(ai_tcc15) AS ai_tcc15,\n  avg(ai_tcc16) AS ai_tcc16,\n  avg(ai_tcc17) AS ai_tcc17,\n  avg(ai_tcc18) AS ai_tcc18,\n  avg(ai_tcc19) AS ai_tcc19,\n  avg(ai_tcc20) AS ai_tcc20\nFROM shs\nWHERE $__timeFilter(\"timestamp\")\nGROUP BY 1\nORDER BY 1;\n"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "kelvin" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('5 minutes', \"timestamp\") AS \"time\",\n  avg(ia_tcx01) AS ia_tcx01,\n  avg(ia_tcx02) AS ia_tcx02,\n  avg(ia_tcx03) AS ia_tcx03,\n  avg(ia_tcx04) AS ia_tcx04,\n  avg(ia_tcx05) AS ia_tcx05,\n  avg(ia_tcx06) AS ia_tcx06,\n  avg(ia_tcx07) AS ia_tcx07,\n  avg(ia_tcx08) AS ia_tcx08,\n  avg(ia_tsd09) AS ia_tsd09,\n  avg(ia_tsd10) AS ia_tsd10,\n  avg(ia_tsd11) AS ia_tsd11,\n  avg(ia_tsd12) AS ia_tsd12,\n  avg(ai_tcc13) AS ai_tcc13,\n  avg(ai_tcc14) AS ai_tcc14,\n  avg(ai_tcc15) AS ai_tcc15,\n  avg(ai_tcc16) AS ai_tcc16,\n  avg(ai_tcc17) AS ai_tcc17,\n  avg(ai_tcc18) AS ai_tcc18,\n  avg(ai_tcc19) AS ai_tcc19,\n  avg(ai_tcc20) AS ai_tcc20\nFROM shs\nWHERE $__timeFilter(\"timestamp\")\nGROUP BY 1\nORDER BY 1;\n"
    }
   ]
  },
  { "title": "GL840", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Pressure",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, POWER(10, 2* (ch01_value - 6.5)) as \"CC10 mag\", POWER(10, 2 * (ch02_value -6.5)) as \"CC10 mid\" FROM gl840\nWHERE ip_address LIKE 'logger1.%'\nORDER BY timestamp DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, ch03_value as \"Magnet\", ch04_value as \"Room\" FROM gl840\nWHERE ip_address LIKE 'logger1.%'\nORDER BY timestamp DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, POWER(10, 2* (ch01_value - 6.5)) as \"CC10 mag\", POWER(10, 2 * (ch02_value -6.5)) as \"CC10 mid\" FROM gl840\nWHERE ip_address LIKE 'logger1.%'\nORDER BY timestamp DESC LIMIT 100000"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, ch03_value as \"Magnet\", ch04_value as \"Room\" FROM gl840\nWHERE ip_address LIKE 'logger1.%'\nORDER BY timestamp DESC LIMIT 100000"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, POWER(10, 2* (ch01_value - 6.5)) as \"CC10 mag\", POWER(10, 2 * (ch02_value -6.5)) as \"CC10 mid\" FROM gl840\nWHERE ip_address LIKE 'logger1.%' OR ip_address LIKE '192.168.%'\nORDER BY timestamp DESC LIMIT 100000"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, ch03_value as \"Magnet\", ch04_value as \"Room\" FROM gl840\nWHERE ip_address LIKE 'logger1.%' OR ip_address LIKE '192.168.%'\nORDER BY timestamp DESC LIMIT 100000"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('5 minute', timestamp) AS minute,\n  avg(ai_ci_ps) AS ai_ci_ps,\n--  avg(ai_v_hall) AS ai_v_hall,\n  avg(ia_v_hall) AS ia_v_hall\n--  avg(ai_v_hall) AS ai_v_hall,\n--  avg(ia_v_hall) AS ia_v_hall\nFROM\n  shs\nWHERE\n  timestamp BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY\n  minute\nORDER BY\n  minute"
    },
    {
     "rawSql": "SELECT timestamp, field as \"probe1\" FROM field WHERE name = 'shs1' ORDER BY timestamp DESC LIMIT 100000"
    },
    {
     "rawSql": "SELECT timestamp, ABS(field) as \"probe2\" FROM field WHERE name = 'shs2' ORDER BY timestamp DESC LIMIT 100000"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('5 minute', timestamp) AS minute,\n  avg(ai_ci_ps) AS ai_ci_ps,\n--  avg(ai_v_hall) AS ai_v_hall,\n  avg(ia_v_hall) AS ia_v_hall\n--  avg(ai_v_hall) AS ai_v_hall,\n--  avg(ia_v_hall) AS ia_v_hall\nFROM\n  shs\nWHERE\n  timestamp BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY\n  minute\nORDER BY\n  minute"
    }
   ]
  },
  { "title": "Omniace / Cryomag", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Omni-ace RA2300MkII",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "rawSql": "SELECT \n timestamp,\n ch01 as \"v41\", ch02 as \"v16\", ch03 as \"v102\", ch05 as \"v112\", ch07 as \"v73\",\n ch08 as \"v35\", ch09 as \"v45-vtot\", ch10 as \"vshunt\", ch11 as \"vbl\", ch12 as \"vps\",\n ch13 as \"vhallx5\", ch15 as \"cbi\", ch16 as \"qdtrg\"\nFROM omniace\nORDER BY timestamp DESC LIMIT 10000"
    }
   ]
  },
  {
   "title": "Cryomag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "rawSql": "SELECT \n timestamp,\n iout, imag, vout, vmag\nFROM cryomag\nORDER BY timestamp DESC LIMIT 10000"
    }
   ]
  },
  {
   "title": "Omni-ace RA2300MkII",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "targets": [
    {
     "rawSql": "SELECT \n timestamp,\n ch01 as \"v41\", ch02 as \"v16\", ch03 as \"v102\", ch05 as \"v112\", ch07 as \"v73\",\n ch08 as \"v35\", ch09 as \"v45-vtot\", ch10 as \"vshunt\", ch11 as \"vbl\", ch12 as \"vps\",\n ch13 as \"vhallx5\", ch15 as \"cbi\", ch16 as \"qdtrg\"\nFROM omniace\nORDER BY timestamp DESC LIMIT 40000"
    }
   ]
  },
  {
   "title": "Cryomag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "rawSql": "SELECT \n timestamp,\n iout, imag, vout, vmag\nFROM cryomag\nORDER BY timestamp DESC LIMIT 40000"
    }
   ]
  }
 ]
}