{
 "title": "Slit",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "IFH / IFV",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, ifh_minus_cor as ifh_minus, ifh_plus_cor as ifh_plus, ifv_minus_cor as ifv_minus, ifv_plus_cor as ifv_plus_cor from slit ORDER BY timestamp DESC LIMIT 1\n"
    }
   ]
  },
  {
   "title": "Momentum slit",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, mom_minus_cor as mom_minus, mom_plus_cor as mom_plus from slit ORDER BY timestamp DESC LIMIT 1\n"
    }
   ]
  },
  {
   "title": "Mass slit 1",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, mass1_minus_cor as mass1_minus, mass1_plus_cor as mass1_plus from slit ORDER BY timestamp DESC LIMIT 1\n"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 10 },
   "targets": [
    { "rawSql": "SELECT * FROM slit" }
   ]
  }
 ]
}