{
 "title": "Summary",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "Accelerator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT run_no from acc ORDER BY timestamp DESC LIMIT 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT opr_mode from acc ORDER BY timestamp DESC LIMIT 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT mr_cycle, sx_splen from acc ORDER BY timestamp DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Last update",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp from acc  ORDER BY timestamp DESC LIMIT 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT mr_power, syim_power from acc ORDER BY timestamp DESC LIMIT 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT mr_p3_intensity, syim_intensity, bdmpim_intensity from acc ORDER BY timestamp DESC LIMIT 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sx_duty, sx_ext_effi from acc ORDER BY timestamp DESC LIMIT 1"
    }
   ]
  },
  { "title": "Magnet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "BSM1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp,\n  key AS name,\n--  value->>'pol'  AS polarity,\n  (value->>'cset')::float8 AS cset,\n  (value->>'cmon')::float8 AS cmon\nFROM magnet,\nLATERAL jsonb_each(magnet_data) AS m(key, value)\nWHERE key = 'BSM1'\nORDER BY timestamp DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "K1.8D1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp,\n  key AS name,\n--  value->>'pol'  AS polarity,\n  (value->>'cset')::float8 AS cset,\n  (value->>'cmon')::float8 AS cmon\nFROM magnet,\nLATERAL jsonb_each(magnet_data) AS m(key, value)\nWHERE key = 'AK18D1'\nORDER BY timestamp DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "K1.8BR D5",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp,\n  key AS name,\n--  value->>'pol'  AS polarity,\n  (value->>'cset')::float8 AS cset,\n  (value->>'cmon')::float8 AS cmon\nFROM magnet,\nLATERAL jsonb_each(magnet_data) AS m(key, value)\nWHERE key = 'K18BRD5'\nORDER BY timestamp DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "D5 field",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "T" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT field\nFROM field\nWHERE name = 'd5' \nORDER BY timestamp DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "ESS1 NEG",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "kvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT neg_vset1 as vset, neg_vmon1 as vmon\nFROM ess\nORDER BY timestamp DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "ESS1 POS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "kvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT pos_vset1 as vset, pos_vmon1 as vmon\nFROM ess\nORDER BY timestamp DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "SHS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "T" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT iout\nFROM cryomag\nORDER BY timestamp DESC\nLIMIT 1"
    },
    {
     "rawSql": "SELECT field as shs1\nFROM field\nWHERE name = 'shs1' \nORDER BY timestamp DESC\nLIMIT 1"
    },
    {
     "rawSql": "SELECT field as shs2\nFROM field\nWHERE name = 'shs2' \nORDER BY timestamp DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "CM1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp,\n  key AS name,\n--  value->>'pol'  AS polarity,\n  (value->>'cset')::float8 AS cset,\n  (value->>'cmon')::float8 AS cmon\nFROM magnet,\nLATERAL jsonb_each(magnet_data) AS m(key, value)\nWHERE key = 'K18CM1'\nORDER BY timestamp DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "CM2",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp,\n  key AS name,\n--  value->>'pol'  AS polarity,\n  (value->>'cset')::float8 AS cset,\n  (value->>'cmon')::float8 AS cmon\nFROM magnet,\nLATERAL jsonb_each(magnet_data) AS m(key, value)\nWHERE key = 'K18CM2'\nORDER BY timestamp DESC LIMIT 1;"
    }
   ]
  },
  { "title": "Slit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp, ifh_minus_cor, ifh_plus_cor, ifv_minus_cor, ifv_plus_cor, mom_minus_cor, mom_plus_cor, mass1_minus_cor, mass1_plus_cor\nFROM slit\nORDER BY timestamp DESC LIMIT 1;"
    }
   ]
  },
  { "title": "Air", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, ch03_value as \"Magnet\", ch04_value as \"Room\" FROM gl840\nWHERE ip_address LIKE 'logger1.%'\nORDER BY timestamp DESC LIMIT 1"
    }
   ]
  },
  { "title": "DAQ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT run_number --, start_time, comment\nFROM hddaq\nORDER BY timestamp DESC LIMIT 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 3, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT start_time --, comment\nFROM hddaq\nORDER BY timestamp DESC LIMIT 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 13, "x": 11, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT comment\nFROM hddaq\nORDER BY timestamp DESC LIMIT 1"
    }
   ]
  }
 ]
}