{
 "title": "Target",
 "description": "Liquid Hydrogen Target",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp\nFROM target\nORDER BY timestamp DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT fan_on, ref_on\nFROM target\nORDER BY timestamp DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT alert_ybox, alert_gl860, alert_h2leak, alert_user\nFROM target\nORDER BY timestamp DESC\nLIMIT 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT hdexhaust_flow\nFROM target\nORDER BY timestamp DESC\nLIMIT 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT press_diff\nFROM target\nORDER BY timestamp DESC\nLIMIT 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT h2leak_1, h2leak_2, h2leak_3\nFROM target\nORDER BY timestamp DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kelvin" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, temp_ref1st, temp_cond_up, temp_cond_dw, temp_tgt_up, temp_tgt_dw, temp_room\nFROM target"
    }
   ]
  },
  {
   "title": "H2 Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Torr" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, h2_press\nFROM target"
    }
   ]
  },
  {
   "title": "Vacuum CC-10",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, vac_cryo, vac_tank\nFROM target"
    }
   ]
  },
  {
   "title": "Heater Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, heater_v\nFROM target"
    }
   ]
  }
 ]
}